### PR TITLE
Added check retry option

### PR DESCRIPTION
**Pull request by AnAverageBeing**
fixed proxies not saving in file issue
added a retries option to recheck proxy x times if it is dead.
this will be very helpful as sometimes proxy do not respond at once.

### CODE REVIEW

**Comment by Z3NTL3** [comment]
> fixed proxies not saving in file issue added a retries option to recheck proxy x times if it is dead. this will be very helpful as sometimes proxy do not respond at once.

Proxy not saving is not a programitical problem it is related to Unix like permissions. Give the script chmod 755 perms will fix this issue.

And as answer to your other question, I will add a retry which can be configured through the command line arg.

**Comment by AnAverageBeing** [comment]
> 

Oh i just open file with Read and write perms idk too much because i have just started learning it i just know java so just put basic think that i can come up with also thanks for your work this tool is really good and i will use it other open source tool that is made to stress test server 

Also if u have time please tell me how i can i improve my retry logic

**Comment by Z3NTL3** [comment]
> > 
> 
> Oh i just open file with Read and write perms idk too much because i have just started learning it i just know java so just put basic think that i can come up with also thanks for your work this tool is really good and i will use it other open source tool that is made to stress test server
> 
> Also if u have time please tell me how i can i improve my retry logic

You will be able to implement your retry logic through the command line args. But currently I am busy so you will need to wait for a week or so. Because I am now busy with some exams etc. Back to your questionm what I will do is to add option flags and within these flags you should be able to provide ``-retry`` option flag with a max value of 15. For example ``-retry 10`` will mean that the script will retry the failed or timed out proxies for 10 times, after the 10th time if it didnt respond it wont be marking it as goods. Otherwise it will.

**Comment by Z3NTL3** [comment]
Hello, we have added command line flags and retry option!

Thanks for your pull request tho, but for me it is not a good way of implementing a retry option as you are just spamming more goroutines for the same proxy. This is inefficient. We have added the retry option in an efficient and good way.

Please pull our update and update your fork. Thanks for your feedback. This is now implemented.

See proof video:
https://www.youtube.com/watch?v=OFt0qkIhX-E

**Comment by AnAverageBeing** [comment]
thanks man

**Pull request closed without merging**
